/**
 * Alptis Santé Pro Plus Product Configuration
 * Mutuelle santé pour travailleurs non salariés (TNS)
 */

import type { ProductConfiguration } from "../../../../shared/types/product";
import type { SanteProPlusFormData } from "../../platforms/alptis/products/sante-pro-plus/transformers/types";

export const ALPTIS_SANTE_PRO_PLUS: ProductConfiguration<SanteProPlusFormData> = {
  platform: "alptis",
  product: "sante_pro_plus",
  flowKey: "alptis_sante_pro_plus",
  category: "sante",
  displayName: "Alptis Santé Pro Plus",
  description: "Mutuelle santé pour travailleurs non salariés (TNS)",

  steps: [
    {
      id: "auth",
      name: "Authentification",
      description: "Connexion à la plateforme Alptis",
      type: "auth",
      required: true,
      method: "login",
      stepClass: "AlptisAuthStep",
      needsCredentials: false,
      needsLead: false,
      maxRetries: 2,
      estimatedDuration: 5000,
    },
    {
      id: "navigation",
      name: "Navigation",
      description: "Accès au formulaire Santé Pro Plus",
      type: "navigation",
      required: true,
      method: "execute",
      stepClass: "AlptisSanteProPlusNavigationStep",
      needsCredentials: false,
      needsLead: false,
      maxRetries: 1,
      estimatedDuration: 3000,
    },
    {
      id: "form-section-1",
      name: "Mise en place",
      description: "Section 1 : Mise en place du contrat (2 champs)",
      type: "form-fill",
      required: true,
      method: "fillMiseEnPlace",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 2000,
    },
    {
      id: "form-section-2",
      name: "Adhérent",
      description: "Section 2 : Informations de l'adhérent (11 champs dont micro-entrepreneur, ville, statut pro)",
      type: "form-fill",
      required: true,
      method: "fillAdherent",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 6000,
    },
    {
      id: "form-section-3",
      name: "Conjoint",
      description: "Section 3 : Informations du conjoint (3 champs, pas de cadre exercice)",
      type: "form-fill",
      required: false,
      conditional: "hasConjoint",
      method: "fillConjoint",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 3000,
    },
    {
      id: "form-section-4",
      name: "Enfants",
      description: "Section 4 : Informations des enfants (2 champs par enfant)",
      type: "form-fill",
      required: false,
      conditional: "hasEnfants",
      method: "fillEnfants",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 4000,
    },
    {
      id: "submit",
      name: "Soumettre",
      description: "Cliquer sur Garanties pour passer à l'étape 2",
      type: "form-fill",
      required: true,
      method: "submit",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: false,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 3000,
    },
    {
      id: "save-garanties",
      name: "Enregistrer",
      description: "Cliquer sur Enregistrer sur la page Garanties",
      type: "form-fill",
      required: true,
      method: "saveGaranties",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: false,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 2000,
    },
    {
      id: "confirm-save",
      name: "Confirmer",
      description: "Cliquer sur 'Enregistrer et continuer' dans le modal de confirmation",
      type: "form-fill",
      required: true,
      method: "confirmSave",
      stepClass: "AlptisSanteProPlusFormFillStep",
      needsLead: false,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 2000,
      isSubmit: true,
    },
  ],

  // Conditional rules to evaluate step conditions
  conditionalRules: {
    hasConjoint: (data: SanteProPlusFormData) => !!data.conjoint,
    hasEnfants: (data: SanteProPlusFormData) => (data.enfants?.length ?? 0) > 0,
  },

  metadata: {
    formUrl: "https://pro.alptis.org/sante-pro-plus/informations-projet/",
    totalSections: 4,
    supportsPartialFill: true,
    requiresBrowser: true,
    supportsScreenshots: true,
    supportsPauseResume: true,
    tags: ["sante", "tns", "independant", "mutuelle", "alptis"],
    complexity: "medium",
    priority: "high",
  },
};
