/**
 * Entoria Pack Famille Product Configuration
 * Formulaire de tarification TNS Santé en 4 étapes
 */

import type { ProductConfiguration } from '../../../../shared/types/product';
import type { PackFamilleFormData } from '../../platforms/entoria/products/pack-famille/transformers/types';

export const ENTORIA_PACK_FAMILLE: ProductConfiguration<PackFamilleFormData> = {
  platform: 'entoria',
  product: 'pack_famille',
  flowKey: 'entoria_pack_famille',
  category: 'sante',
  displayName: 'Entoria Pack Famille',
  description: 'Tarification TNS Santé avec option famille',

  steps: [
    {
      id: 'auth',
      name: 'Authentification',
      description: 'Connexion à la plateforme Entoria',
      type: 'auth',
      required: true,
      method: 'login',
      stepClass: 'EntoriaAuthStep',
      needsCredentials: true,
      needsLead: false,
      maxRetries: 2,
      estimatedDuration: 5000,
    },
    {
      id: 'navigation',
      name: 'Navigation',
      description: 'Accès au formulaire TNS Santé',
      type: 'navigation',
      required: true,
      method: 'execute',
      stepClass: 'EntoriaPackFamilleNavigationStep',
      needsCredentials: false,
      needsLead: false,
      maxRetries: 1,
      estimatedDuration: 3000,
    },
    {
      id: 'step1-profil',
      name: 'Profil',
      description: 'Étape 1 : Profil de l\'entrepreneur',
      type: 'form-fill',
      required: true,
      method: 'fillProfil',
      stepClass: 'EntoriaPackFamilleFormFillStep',
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 5000,
    },
    {
      id: 'step1-submit',
      name: 'Valider Profil',
      description: 'Cliquer sur CONTINUER',
      type: 'form-fill',
      required: true,
      method: 'submitProfil',
      stepClass: 'EntoriaPackFamilleFormFillStep',
      needsLead: false,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 2000,
    },
    {
      id: 'step2-besoin',
      name: 'Besoin',
      description: 'Étape 2 : Recueil des besoins',
      type: 'form-fill',
      required: true,
      method: 'fillBesoin',
      stepClass: 'EntoriaPackFamilleFormFillStep',
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 2000,
    },
    {
      id: 'step2-submit',
      name: 'Valider Besoin',
      description: 'Cliquer sur suivant',
      type: 'form-fill',
      required: true,
      method: 'submitBesoin',
      stepClass: 'EntoriaPackFamilleFormFillStep',
      needsLead: false,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 2000,
    },
    {
      id: 'step3-garanties',
      name: 'Garanties',
      description: 'Étape 3 : Choix des garanties',
      type: 'form-fill',
      required: true,
      method: 'fillGaranties',
      stepClass: 'EntoriaPackFamilleFormFillStep',
      needsLead: true,
      needsCredentials: false,
      maxRetries: 1,
      estimatedDuration: 5000,
    },
  ],

  conditionalRules: {
    hasConjoint: (data: PackFamilleFormData) => data.garanties?.avec_conjoint ?? false,
    hasEnfants: (data: PackFamilleFormData) => data.garanties?.avec_enfants ?? false,
  },

  metadata: {
    formUrl: 'https://espacecourtier.entoria.fr/tarification/10775400299/profil/tns/sante',
    totalSections: 4,
    supportsPartialFill: true,
    requiresBrowser: true,
    supportsScreenshots: true,
    supportsPauseResume: true,
    tags: ['sante', 'tns', 'famille', 'mutuelle', 'entoria', 'tarification'],
    complexity: 'simple',
    priority: 'high',
  },
};
