import type {
  LeadFormSchema,
  FieldDefinition,
  SectionDefinition,
} from "@/shared/types/form-schema";

/**
 * Section definitions for the Lead form
 */
const SECTIONS: SectionDefinition[] = [
  {
    id: "subscriber",
    label: "Adhérent",
    description: "Informations personnelles de l'adhérent principal",
    icon: "User",
    order: 1,
    collapsible: true,
    defaultCollapsed: false,
  },
  {
    id: "project",
    label: "Projet",
    description: "Détails du projet d'assurance",
    icon: "FileText",
    order: 2,
    collapsible: true,
    defaultCollapsed: false,
  },
  {
    id: "conjoint",
    label: "Conjoint",
    description: "Informations du conjoint",
    icon: "Users",
    order: 3,
    collapsible: true,
    defaultCollapsed: true,
    visible: {
      field: "project.conjoint",
      operator: "notEmpty",
    },
  },
  {
    id: "children",
    label: "Enfants",
    description: "Informations des enfants à charge",
    icon: "Baby",
    order: 4,
    collapsible: true,
    defaultCollapsed: true,
    repeatable: true,
    minItems: 0,
    maxItems: 10,
    itemLabel: "Enfant {index}",
    visible: {
      field: "subscriber.nombreEnfants",
      operator: "gt",
      value: 0,
    },
  },
  {
    id: "coverage",
    label: "Niveaux de garantie",
    description: "Niveaux de couverture souhaités",
    icon: "Shield",
    order: 5,
    collapsible: true,
    defaultCollapsed: false,
  },
];

/**
 * Common validation patterns
 */
const PATTERNS = {
  date: "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$",
  codePostal: "^\\d{5}$",
  nom: "^[a-zA-ZÀ-ÿ\\-\\s']+$",
  email: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
  tel: "^[0-9\\s\\.\\-\\+]+$",
};

/**
 * Field definitions for the Lead form
 */
const FIELDS: FieldDefinition[] = [
  // ========== SUBSCRIBER SECTION ==========
  {
    name: "civilite",
    path: "subscriber.civilite",
    label: "Civilité",
    type: "select",
    options: [
      { value: "M", label: "Monsieur" },
      { value: "Mme", label: "Madame" },
    ],
    required: true,
    section: "subscriber",
    order: 1,
  },
  {
    name: "nom",
    path: "subscriber.nom",
    label: "Nom",
    placeholder: "Dupont",
    type: "text",
    required: true,
    validations: [
      {
        type: "pattern",
        value: PATTERNS.nom,
        message: "Le nom ne peut contenir que des lettres, tirets et apostrophes",
      },
      {
        type: "minLength",
        value: 2,
        message: "Le nom doit contenir au moins 2 caractères",
      },
      {
        type: "maxLength",
        value: 50,
        message: "Le nom ne peut pas dépasser 50 caractères",
      },
    ],
    section: "subscriber",
    order: 2,
  },
  {
    name: "prenom",
    path: "subscriber.prenom",
    label: "Prénom",
    placeholder: "Jean",
    type: "text",
    required: true,
    validations: [
      {
        type: "pattern",
        value: PATTERNS.nom,
        message: "Le prénom ne peut contenir que des lettres, tirets et apostrophes",
      },
      {
        type: "minLength",
        value: 2,
        message: "Le prénom doit contenir au moins 2 caractères",
      },
    ],
    section: "subscriber",
    order: 3,
  },
  {
    name: "dateNaissance",
    path: "subscriber.dateNaissance",
    label: "Date de naissance",
    placeholder: "JJ/MM/AAAA",
    type: "date",
    required: true,
    pattern: PATTERNS.date,
    patternMessage: "Format attendu: JJ/MM/AAAA",
    helpText: "L'adhérent doit avoir entre 18 et 110 ans",
    computed: {
      type: "age",
      sourceField: "subscriber.dateNaissance",
    },
    section: "subscriber",
    order: 4,
  },
  {
    name: "email",
    path: "subscriber.email",
    label: "Email",
    placeholder: "jean.dupont@email.com",
    type: "email",
    required: false,
    pattern: PATTERNS.email,
    patternMessage: "Adresse email invalide",
    section: "subscriber",
    order: 5,
  },
  {
    name: "telephone",
    path: "subscriber.telephone",
    label: "Téléphone",
    placeholder: "06 12 34 56 78",
    type: "tel",
    required: false,
    pattern: PATTERNS.tel,
    patternMessage: "Numéro de téléphone invalide",
    section: "subscriber",
    order: 6,
  },
  {
    name: "adresse",
    path: "subscriber.adresse",
    label: "Adresse",
    placeholder: "12 rue de la Paix",
    type: "text",
    required: false,
    section: "subscriber",
    order: 7,
  },
  {
    name: "codePostal",
    path: "subscriber.codePostal",
    label: "Code postal",
    placeholder: "75001",
    type: "text",
    required: true,
    pattern: PATTERNS.codePostal,
    patternMessage: "Le code postal doit contenir 5 chiffres",
    section: "subscriber",
    order: 8,
  },
  {
    name: "ville",
    path: "subscriber.ville",
    label: "Ville",
    placeholder: "Paris",
    type: "text",
    required: false,
    section: "subscriber",
    order: 9,
  },
  {
    name: "profession",
    path: "subscriber.profession",
    label: "Profession",
    placeholder: "Cadre",
    type: "text",
    required: false,
    section: "subscriber",
    order: 10,
  },
  {
    name: "regimeSocial",
    path: "subscriber.regimeSocial",
    label: "Régime social",
    type: "select",
    options: [
      { value: "salarie", label: "Salarié" },
      { value: "tns", label: "TNS (Travailleur Non Salarié)" },
      { value: "retraite", label: "Retraité" },
      { value: "fonctionnaire", label: "Fonctionnaire" },
      { value: "sans_emploi", label: "Sans emploi" },
      { value: "etudiant", label: "Étudiant" },
      { value: "autre", label: "Autre" },
    ],
    required: false,
    section: "subscriber",
    order: 11,
  },
  {
    name: "nombreEnfants",
    path: "subscriber.nombreEnfants",
    label: "Nombre d'enfants",
    type: "number",
    min: 0,
    max: 10,
    defaultValue: 0,
    helpText: "Enfants à charge de moins de 27 ans",
    section: "subscriber",
    order: 12,
  },

  // ========== PROJECT SECTION ==========
  {
    name: "dateEffet",
    path: "project.dateEffet",
    label: "Date d'effet souhaitée",
    placeholder: "JJ/MM/AAAA",
    type: "date",
    required: false,
    pattern: PATTERNS.date,
    patternMessage: "Format attendu: JJ/MM/AAAA",
    section: "project",
    order: 1,
  },
  {
    name: "moisEcheance",
    path: "project.moisEcheance",
    label: "Mois d'échéance",
    type: "select",
    options: [
      { value: "01", label: "Janvier" },
      { value: "02", label: "Février" },
      { value: "03", label: "Mars" },
      { value: "04", label: "Avril" },
      { value: "05", label: "Mai" },
      { value: "06", label: "Juin" },
      { value: "07", label: "Juillet" },
      { value: "08", label: "Août" },
      { value: "09", label: "Septembre" },
      { value: "10", label: "Octobre" },
      { value: "11", label: "Novembre" },
      { value: "12", label: "Décembre" },
    ],
    required: false,
    section: "project",
    order: 2,
  },
  {
    name: "actuellementAssure",
    path: "project.actuellementAssure",
    label: "Actuellement assuré",
    type: "checkbox",
    defaultValue: false,
    section: "project",
    order: 3,
  },
  {
    name: "assureurActuel",
    path: "project.assureurActuel",
    label: "Assureur actuel",
    placeholder: "Nom de l'assureur",
    type: "text",
    required: false,
    visible: {
      field: "project.actuellementAssure",
      operator: "eq",
      value: true,
    },
    section: "project",
    order: 4,
  },
  {
    name: "formuleChoisie",
    path: "project.formuleChoisie",
    label: "Formule choisie",
    type: "text",
    required: false,
    section: "project",
    order: 5,
  },
  {
    name: "besoinAssuranceSante",
    path: "project.besoinAssuranceSante",
    label: "Besoin en assurance santé",
    type: "text",
    required: false,
    helpText: "Décrivez vos besoins spécifiques",
    section: "project",
    order: 6,
  },
  {
    name: "source",
    path: "project.source",
    label: "Source du lead",
    type: "text",
    required: false,
    readOnly: true,
    section: "project",
    order: 7,
  },

  // ========== CONJOINT SECTION ==========
  {
    name: "conjoint.dateNaissance",
    path: "project.conjoint.dateNaissance",
    label: "Date de naissance",
    placeholder: "JJ/MM/AAAA",
    type: "date",
    required: {
      field: "project.conjoint",
      operator: "notEmpty",
    },
    pattern: PATTERNS.date,
    patternMessage: "Format attendu: JJ/MM/AAAA",
    helpText: "Le conjoint doit avoir entre 18 et 110 ans",
    computed: {
      type: "age",
      sourceField: "project.conjoint.dateNaissance",
    },
    section: "conjoint",
    order: 1,
  },
  {
    name: "conjoint.profession",
    path: "project.conjoint.profession",
    label: "Profession",
    placeholder: "Cadre",
    type: "text",
    required: false,
    section: "conjoint",
    order: 2,
  },
  {
    name: "conjoint.regimeSocial",
    path: "project.conjoint.regimeSocial",
    label: "Régime social",
    type: "select",
    options: [
      { value: "salarie", label: "Salarié" },
      { value: "tns", label: "TNS (Travailleur Non Salarié)" },
      { value: "retraite", label: "Retraité" },
      { value: "fonctionnaire", label: "Fonctionnaire" },
      { value: "sans_emploi", label: "Sans emploi" },
      { value: "etudiant", label: "Étudiant" },
      { value: "autre", label: "Autre" },
    ],
    required: false,
    section: "conjoint",
    order: 3,
  },

  // ========== CHILDREN SECTION (template for repeatable) ==========
  {
    name: "children[].dateNaissance",
    path: "children[].dateNaissance",
    label: "Date de naissance",
    placeholder: "JJ/MM/AAAA",
    type: "date",
    required: true,
    pattern: PATTERNS.date,
    patternMessage: "Format attendu: JJ/MM/AAAA",
    helpText: "L'enfant doit avoir entre 0 et 27 ans",
    computed: {
      type: "age",
      sourceField: "children[].dateNaissance",
    },
    section: "children",
    order: 1,
  },
  {
    name: "children[].regimeSocial",
    path: "children[].regimeSocial",
    label: "Régime social",
    type: "select",
    options: [
      { value: "salarie", label: "Salarié" },
      { value: "etudiant", label: "Étudiant" },
      { value: "sans_emploi", label: "Sans emploi" },
      { value: "autre", label: "Autre" },
    ],
    required: false,
    section: "children",
    order: 2,
  },

  // ========== COVERAGE SECTION ==========
  {
    name: "soinsMedicaux",
    path: "project.soinsMedicaux",
    label: "Soins médicaux",
    helpText: "Niveau de remboursement souhaité (1 = minimum, 4 = maximum)",
    type: "slider",
    min: 1,
    max: 4,
    step: 1,
    defaultValue: 2,
    section: "coverage",
    order: 1,
  },
  {
    name: "hospitalisation",
    path: "project.hospitalisation",
    label: "Hospitalisation",
    helpText: "Niveau de remboursement souhaité (1 = minimum, 4 = maximum)",
    type: "slider",
    min: 1,
    max: 4,
    step: 1,
    defaultValue: 2,
    section: "coverage",
    order: 2,
  },
  {
    name: "optique",
    path: "project.optique",
    label: "Optique",
    helpText: "Niveau de remboursement souhaité (1 = minimum, 4 = maximum)",
    type: "slider",
    min: 1,
    max: 4,
    step: 1,
    defaultValue: 2,
    section: "coverage",
    order: 3,
  },
  {
    name: "dentaire",
    path: "project.dentaire",
    label: "Dentaire",
    helpText: "Niveau de remboursement souhaité (1 = minimum, 4 = maximum)",
    type: "slider",
    min: 1,
    max: 4,
    step: 1,
    defaultValue: 2,
    section: "coverage",
    order: 4,
  },
];

/**
 * Complete Lead Form Schema
 */
export const LEAD_FORM_SCHEMA: LeadFormSchema = {
  version: "1.0.0",
  sections: SECTIONS,
  fields: FIELDS,
  computedFields: [
    { type: "age", sourceField: "subscriber.dateNaissance" },
    { type: "age", sourceField: "project.conjoint.dateNaissance" },
  ],
};
